/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.CardLayout;
import java.awt.Container;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author ACER
 */
public class PilihGambarButtonFullScreen extends javax.swing.JFrame {


    /**
     * Creates new form button
     */
    public PilihGambarButtonFullScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gambar1BTN = new javax.swing.JButton();
        gambar2BTN = new javax.swing.JButton();
        gambar3BTN = new javax.swing.JButton();
        keluarBTN = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        gambar1LBL = new javax.swing.JLabel();
        gambar2LBL = new javax.swing.JLabel();
        gambar3LBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 255, 153));

        gambar1BTN.setText("Gambar 1");
        gambar1BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gambar1BTNActionPerformed(evt);
            }
        });
        jPanel1.add(gambar1BTN);

        gambar2BTN.setText("Gambar 2");
        gambar2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gambar2BTNActionPerformed(evt);
            }
        });
        jPanel1.add(gambar2BTN);

        gambar3BTN.setText("Gambar 3");
        gambar3BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gambar3BTNActionPerformed(evt);
            }
        });
        jPanel1.add(gambar3BTN);

        keluarBTN.setText("Keluar");
        keluarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarBTNActionPerformed(evt);
            }
        });
        jPanel1.add(keluarBTN);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        imagePanel.setBackground(new java.awt.Color(0, 0, 255));
        imagePanel.setLayout(new java.awt.CardLayout());

        gambar1LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gambar1LBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/bjb.jpg"))); // NOI18N
        imagePanel.add(gambar1LBL, "0");

        gambar2LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gambar2LBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/pas.jpg"))); // NOI18N
        imagePanel.add(gambar2LBL, "1");

        gambar3LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gambar3LBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/uniska.jpg"))); // NOI18N
        imagePanel.add(gambar3LBL, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_keluarBTNActionPerformed

    private void gambar1BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gambar1BTNActionPerformed
    CardLayout c1 = (CardLayout) (imagePanel.getLayout());
    c1.show((Container) imagePanel, "0");
    }//GEN-LAST:event_gambar1BTNActionPerformed

    private void gambar2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gambar2BTNActionPerformed
    CardLayout c1 = (CardLayout) (imagePanel.getLayout());
    c1.show((Container) imagePanel, "1");
    }//GEN-LAST:event_gambar2BTNActionPerformed

    private void gambar3BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gambar3BTNActionPerformed
    CardLayout c1 = (CardLayout) (imagePanel.getLayout());
    c1.show((Container) imagePanel, "2");
    }//GEN-LAST:event_gambar3BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihGambarButtonFullScreen fullFrame = new PilihGambarButtonFullScreen();
                
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                new PilihGambarButtonFullScreen().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gambar1BTN;
    private javax.swing.JLabel gambar1LBL;
    private javax.swing.JButton gambar2BTN;
    private javax.swing.JLabel gambar2LBL;
    private javax.swing.JButton gambar3BTN;
    private javax.swing.JLabel gambar3LBL;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton keluarBTN;
    // End of variables declaration//GEN-END:variables



}
